/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FlowboardRouteImport } from './routes/flowboard'
import { Route as IndexRouteImport } from './routes/index'

const FlowboardRoute = FlowboardRouteImport.update({
  id: '/flowboard',
  path: '/flowboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flowboard': typeof FlowboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flowboard': typeof FlowboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flowboard': typeof FlowboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flowboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flowboard'
  id: '__root__' | '/' | '/flowboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowboardRoute: typeof FlowboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/flowboard': {
      id: '/flowboard'
      path: '/flowboard'
      fullPath: '/flowboard'
      preLoaderRoute: typeof FlowboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowboardRoute: FlowboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
